name: Release Luger.Configuration.CommandLine
run-name: Release of Luger.Configuration.CommandLine (tag ${{ github.ref_name }}) by @${{ github.actor }}

on:
  push:
    tags:
    - "Config.CommandLine/v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release_configuration_commandline:
    uses: ./.github/workflows/release.yml
    with:
      project-name: Configuration.CommandLine
      project-file: src/Config.CommandLine/Config.CommandLine.csproj
      test-project-file: /tests/Config.CommandLine.Tests/Config.CommandLine.Tests.csproj"
    secrets:
      NUGET_API_KEY: ${{ secrets.PUSH_TO_NUGET }}

