name: Release Luger.Functional.State
run-name: Release of Luger.Functional.State (tag ${{ github.ref_name }}) by @${{ github.actor }}

on:
  push:
    tags:
    - "Functional.State/v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release_functional_state_job:
    uses: ./.github/workflows/release.yml
    with:
      project-name: Functional.State
      project-file: Functional/State/src/Functional.State.csproj
      test-project-file: Functional/State/tests/Functional.State.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.PUSH_TO_NUGET }}
