name: Release Luger.Functional.Maybe
run-name: Release of Luger.Functional.Maybe (${GITHUB_REF_NAME##*/}) by @${GITHUB_ACTOR}

on:
  push:
    tags:
    - "Functional.Maybe/v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release_functional_maybe_job:
    uses: ./.github/workflows/release.yml
    with:
      project-name: Functional.Maybe
      project-file: ${GITHUB_WORKSPACE}/Functional/Maybe/src/Functional.Maybe.csproj
      test-project-file: ${GITHUB_WORKSPACE}/Functional/Maybe/tests/Functional.Maybe.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.PUSH_TO_NUGET }}
