name: Release Luger.Functional.Maybe

env:
  PROJ_NAME: Functional.Maybe
  PROJ_FILE: "${{ github.workspace }}/Functional/Maybe/src/Functional.Maybe.csproj"

on:
  push:
    tags:
    - "Functional.Maybe/v[0-9]+.[0-9]+.[0-9]+"
    - "Functional.Maybe/v[0-9]+.[0-9]+.[0-9]+-[0-9A-Za-z]+"
    - "Functional.Maybe/v[0-9]+.[0-9]+.[0-9]+-[0-9A-Za-z]+-[0-9A-Za-z]+"  # Accomodate at least one dash in pre-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify commit exists in origin/trunk
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/trunk

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/${PROJ_NAME}\/v/}" >> $GITHUB_ENV

    - name: Install xmllint
      run: sudo apt-get -y install libxml2-utils

    - name: Verify installation
      run: xmllint --version

    - name: Verify tag represents version in project file
      env:
        VERIFY_VERSION: "${{ github.workspace }}/.github/scripts/verifyversion.sh"
      run: |
        chmod +x ${VERIFY_VERSION}
        ${VERIFY_VERSION} ${VERSION} ${PROJ_FILE}

    - name: Build
      run: dotnet build ${PROJ_FILE} --configuration Release /p:Version=${VERSION}

    - name: Test
      env:
        TEST_PROJ_FILE: "${{ github.workspace }}/Functional/Maybe/tests/${{ env.PROJ_NAME }}.Tests.csproj"
      run: dotnet test ${TEST_PROJ_FILE} --configuration Release /p:Version=${VERSION}

    - name: Pack
      run: dotnet pack ${PROJ_FILE} --configuration Release /p:Version=${VERSION} --no-build --output .

    - name: Push to GitHub Packages
      run: |
        dotnet nuget add source --username chamalulu --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/chamalulu/index.json"
        dotnet nuget push Luger.Functional.Maybe.${VERSION}.nupkg --source github

    - name: Push to NuGet
      run: |
        dotnet nuget add source --username chamalulu --password ${{ secrets.PUSH_TO_NUGET }} --store-password-in-clear-text --name nuget "https://api.nuget.org/v3/index.json"
        dotnet nuget push Luger.Functional.Maybe.${VERSION}.nupkg --source nuget
